import type { Diet, Disease, Patient } from "./types";

export const diseases: Disease[] = [
  { id: "dm2", name: "Diabetes mellitus tipo 2", shortName: "Diabetes tipo 2" },
  { id: "hta", name: "Hipertensión arterial", shortName: "Hipertensión" },
  { id: "celiac", name: "Enfermedad celíaca", shortName: "Celiaquía" },
];

export const patients: Patient[] = [
  {
    id: "pat-001",
    name: "Laura Martínez",
    document: "HC-2048",
    age: 52,
    sex: "Femenino",
    diseaseIds: ["dm2"],
    allergies: ["frutos secos"],
    incompatibilities: ["lactosa"],
    currentTreatment: "Control metabólico y seguimiento trimestral",
  },
  {
    id: "pat-002",
    name: "Andrés Gómez",
    document: "HC-3176",
    age: 45,
    sex: "Masculino",
    diseaseIds: ["hta"],
    allergies: ["pescado"],
    incompatibilities: [],
    currentTreatment: "Control de presión arterial",
  },
  {
    id: "pat-003",
    name: "Sofía Ramírez",
    document: "HC-4921",
    age: 34,
    sex: "Femenino",
    diseaseIds: ["celiac"],
    allergies: ["huevo"],
    incompatibilities: ["gluten"],
    currentTreatment: "Dieta de exclusión de gluten",
  },
];

export const diets: Diet[] = [
  {
    id: "diet-001",
    name: "Plan vegetal de bajo índice glucémico",
    summary: "Plan equilibrado, rico en fibra y con carbohidratos de absorción lenta.",
    objective: "Apoyar el control de la glucemia y mantener una ingesta estable durante el día.",
    diseaseIds: ["dm2"],
    calories: "1.700–1.900 kcal/día",
    duration: "8 semanas con reevaluación",
    frequency: "3 comidas principales y 2 refrigerios",
    route: "Oral",
    ingredients: [
      { name: "Quinoa" },
      { name: "Lentejas" },
      { name: "Aguacate" },
      { name: "Espinaca" },
      { name: "Arándanos" },
    ],
    recommendations: [
      "Distribuir los carbohidratos durante el día.",
      "Priorizar alimentos frescos y sin azúcares añadidos.",
      "Registrar la respuesta glucémica según indicación médica.",
    ],
  },
  {
    id: "diet-002",
    name: "Mediterránea para control metabólico",
    summary: "Patrón mediterráneo con grasas saludables, vegetales y cereales integrales.",
    objective: "Mejorar el perfil metabólico y favorecer el control glucémico.",
    diseaseIds: ["dm2", "hta"],
    calories: "1.800–2.000 kcal/día",
    duration: "12 semanas con seguimiento",
    frequency: "3 comidas principales y 1 refrigerio",
    route: "Oral",
    ingredients: [
      { name: "Aceite de oliva" },
      { name: "Garbanzos" },
      { name: "Nueces", allergens: ["frutos secos"] },
      { name: "Tomate" },
      { name: "Avena integral" },
    ],
    recommendations: [
      "Mantener porciones controladas de cereales integrales.",
      "Evitar productos ultraprocesados.",
      "Ajustar el aporte energético según evolución clínica.",
    ],
  },
  {
    id: "diet-003",
    name: "DASH reducida en sodio",
    summary: "Plan con bajo contenido de sodio y alto aporte de frutas y verduras.",
    objective: "Contribuir al control de la presión arterial.",
    diseaseIds: ["hta", "dm2"],
    calories: "1.800–2.100 kcal/día",
    duration: "10 semanas con control clínico",
    frequency: "4 ingestas al día",
    route: "Oral",
    ingredients: [
      { name: "Avena" },
      { name: "Yogur natural", incompatibilities: ["lactosa"] },
      { name: "Frutos rojos" },
      { name: "Pechuga de pollo" },
      { name: "Espinaca" },
    ],
    recommendations: [
      "Limitar el sodio de preparación.",
      "Preferir alimentos frescos.",
      "Verificar la presión arterial de acuerdo con el seguimiento médico.",
    ],
  },
  {
    id: "diet-004",
    name: "Cardiovascular sin pescado",
    summary: "Plan cardioprotector basado en legumbres, semillas y vegetales.",
    objective: "Apoyar el control de la presión arterial sin incluir pescado.",
    diseaseIds: ["hta"],
    calories: "1.900–2.100 kcal/día",
    duration: "8 semanas con seguimiento",
    frequency: "3 comidas principales y 1 refrigerio",
    route: "Oral",
    ingredients: [
      { name: "Lentejas" },
      { name: "Semillas de chía" },
      { name: "Aguacate" },
      { name: "Brócoli" },
      { name: "Arroz integral" },
    ],
    recommendations: [
      "Evitar sal añadida durante la preparación.",
      "Mantener hidratación suficiente.",
      "Preferir métodos de cocción al vapor u horno.",
    ],
  },
  {
    id: "diet-005",
    name: "Nórdica cardioprotectora",
    summary: "Plan rico en vegetales, cereales integrales y ácidos grasos omega-3.",
    objective: "Favorecer la salud cardiovascular y el control de la presión arterial.",
    diseaseIds: ["hta"],
    calories: "2.000–2.200 kcal/día",
    duration: "10 semanas con revisión",
    frequency: "4 ingestas al día",
    route: "Oral",
    ingredients: [
      { name: "Salmón", allergens: ["pescado"] },
      { name: "Avena" },
      { name: "Remolacha" },
      { name: "Repollo" },
      { name: "Manzana" },
    ],
    recommendations: [
      "Controlar el sodio total del día.",
      "Priorizar grasas insaturadas.",
      "Combinar con actividad física indicada por el profesional.",
    ],
  },
  {
    id: "diet-006",
    name: "Sin gluten de base vegetal",
    summary: "Plan libre de gluten, con proteínas vegetales y alimentos naturalmente aptos.",
    objective: "Mantener una alimentación completa evitando la exposición al gluten.",
    diseaseIds: ["celiac"],
    calories: "1.700–1.900 kcal/día",
    duration: "Permanente con seguimiento",
    frequency: "3 comidas principales y 2 refrigerios",
    route: "Oral",
    ingredients: [
      { name: "Quinoa certificada" },
      { name: "Arroz" },
      { name: "Garbanzos" },
      { name: "Calabacín" },
      { name: "Frutas frescas" },
    ],
    recommendations: [
      "Evitar contaminación cruzada.",
      "Verificar el etiquetado sin gluten.",
      "Usar utensilios separados cuando sea necesario.",
    ],
  },
  {
    id: "diet-007",
    name: "Sin gluten alta en proteína",
    summary: "Plan libre de gluten con fuentes animales y vegetales de proteína.",
    objective: "Mantener una dieta libre de gluten con aporte proteico suficiente.",
    diseaseIds: ["celiac"],
    calories: "1.900–2.100 kcal/día",
    duration: "Permanente con control periódico",
    frequency: "4 ingestas al día",
    route: "Oral",
    ingredients: [
      { name: "Huevo", allergens: ["huevo"] },
      { name: "Pechuga de pollo" },
      { name: "Papa" },
      { name: "Quinoa certificada" },
      { name: "Zanahoria" },
    ],
    recommendations: [
      "Confirmar certificación libre de gluten.",
      "Evitar preparación conjunta con cereales con gluten.",
      "Realizar seguimiento nutricional periódico.",
    ],
  },
];
